// "use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Layout from "@/components/Layout";
import { ToastContainer } from 'react-toastify';
import { QueryProvider } from "@/providers/queryProvider";
import { AuthProvider } from "@/providers/sessionProvider";
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import { LangProvider } from "@/context/LangContext";
// import "../i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>
            <LangProvider>
              <Layout>
                {children}
                <ToastContainer />
              </Layout>
            </LangProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
